[package]
name = "windows_bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows_macros = { path = "../macros", version = "0.18.0" }
windows_gen = { path = "../gen", version = "0.18.0" }
